version: '3.1'

services:
  db:
    image: postgres:13-alpine
    container_name: greenlight-db
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    networks:
      - app

  mailhog:
    image: mailhog/mailhog:latest
    container_name: greenlight-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app

networks:
  app:
    driver: bridge
