###
POST http://localhost:4000/v1/users

{"name": "Alice Smith", "email": "alice@example.com", "password": "pa55word"}


###
POST http://localhost:4000/v1/users

{"name": "", "email": "bob@invalid.", "password": "pass"}